services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
      - "9001:9001"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
